apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: tonywr/web-app
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
          - name: NEXTAUTH_SECRET
            value: somethingreallyreallysecret
          - name: NEXTAUTH_URL
            value: https://app.carsties.com
          - name: API_URL
            value: http://gateway-clusterip/
          - name: ID_URL
            value: https://id.miji.com.au
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-clusterip
spec:
  type: ClusterIP
  selector:
    app: webapp
  ports:
  - port: 3000
    targetPort: 3000
    name: web
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-lb
spec:
  type: LoadBalancer
  selector:
    app: webapp
  ports:
  - port: 3000
    targetPort: 3000
  